[project]
name = "ha-minimqtt"
version = "0.0.1"
authors = [
    { name="E.A. Graham, Jr." },
]
description = "Home-Assistant MQTT client and devices for CircuitPython"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: CircuitPython",
]
dependencies = [
    "adafruit-circuitpython-minimqtt>=8.0.3",
    "adafruit-circuitpython-pixelbuf>=2.0.10",
]

[project.urls]
Homepage = "https://github.com/EAGrahamJr/ha-minimqtt"
Issues = "https://github.com/EAGrahamJr/ha-minimqtt/issues"

[dependency-groups]
dev = [
    "paho-mqtt>=2.1.0",
    "pytest>=8.3.5",
    "ruff>=0.14.10",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

